language: node_js

os:
  - osx
  - linux

node_js:
  - "0.10"
  - "4.2.3"

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

sudo: false

after_success:
 - if [[ $(uname -s) == 'Linux' ]] && [[ ${TRAVIS_NODE_VERSION} == "0.10" ]]; then npm run coverage; fi;
